os: linux
dist: xenial
language: perl
perl:
  - "5.14"
  - "5.26"

before_install:
  - "sudo apt-get update"
  - "sudo apt-get install -y r-base"
  - "cpanm --sudo -v --installdeps --notest --cpanfile cpanfile ."

notifications:
  email:
    on_failure: always
