os: linux
dist: xenial
language: perl
perl:
  - "5.26"

before_install:
  # Inline::CPP is optional, required by transcripts2cdsCPP.pl
  - cpanm --sudo -v --installdeps --notest --cpanfile cpanfile .
